name: Interacting with CML using API
description: Demonstrating examples of using API.
author: Cloudera Inc.
specification_version: 1.0
prototype_version: 2.0
date: "2022-04-05"

runtimes:
  - editor: JupyterLab
    kernel: Python 3.9
    edition: Standard
